USE DATABASE PAYMENTS_DWH;
USE SCHEMA CORE;

-- 1. Semi-structured data: store raw gateway payloads

CREATE OR REPLACE TABLE RAW_GATEWAY_EVENTS (
    EVENT_ID       VARCHAR      NOT NULL,
    RECEIVED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    GATEWAY_NAME   VARCHAR,
    PAYLOAD        VARIANT      -- JSON from payment gateway
);

-- Example query parsing JSON
SELECT
    EVENT_ID,
    RECEIVED_AT,
    PAYLOAD:"transaction_id"::string      AS transaction_id,
    PAYLOAD:"card":{"bin"}::string       AS card_bin,
    PAYLOAD:"amount"::number(18,2)       AS amount,
    PAYLOAD:"currency"::string           AS currency
FROM RAW_GATEWAY_EVENTS
WHERE PAYLOAD:"status"::string = 'CAPTURED';

-- 2. Time Travel & Fail-safe usage examples

-- Assume FACT_PAYMENT was accidentally truncated. You can time travel:
-- SELECT * FROM FACT_PAYMENT AT (TIMESTAMP => DATEADD('minute', -5, CURRENT_TIMESTAMP()));

-- Or restore a table:
-- CREATE OR REPLACE TABLE FACT_PAYMENT_RESTORE CLONE FACT_PAYMENT AT (TIMESTAMP => DATEADD('minute', -5, CURRENT_TIMESTAMP()));

-- 3. Cloning for dev/test

CREATE OR REPLACE SCHEMA PAYMENTS_DWH.CORE_DEV CLONE PAYMENTS_DWH.CORE;

-- 4. RBAC: roles, grants, and warehouses (simplified)

USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE PAYMENTS_READONLY;
CREATE OR REPLACE ROLE PAYMENTS_ANALYST;

GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE PAYMENTS_ANALYST;
GRANT USAGE ON DATABASE PAYMENTS_DWH TO ROLE PAYMENTS_ANALYST, PAYMENTS_READONLY;
GRANT USAGE ON SCHEMA PAYMENTS_DWH.CORE TO ROLE PAYMENTS_ANALYST, PAYMENTS_READONLY;

GRANT SELECT ON ALL TABLES IN SCHEMA PAYMENTS_DWH.CORE TO ROLE PAYMENTS_READONLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PAYMENTS_DWH.CORE TO ROLE PAYMENTS_ANALYST;

-- 5. Dynamic data masking for PII

USE ROLE SECURITYADMIN;

CREATE OR REPLACE MASKING POLICY MASK_EMAIL AS
  (VAL STRING) RETURNS STRING ->
    CASE
      WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SECURITYADMIN', 'PAYMENTS_ANALYST') THEN VAL
      ELSE REGEXP_REPLACE(VAL, '(^.).+(@.+$)', '\\1***\\2')
    END;

ALTER TABLE DIM_CUSTOMER
  MODIFY COLUMN EMAIL SET MASKING POLICY MASK_EMAIL;

-- 6. Row Access Policy example (governance)

CREATE OR REPLACE ROW ACCESS POLICY RAP_COUNTRY_FILTER AS
  (COUNTRY_CODE STRING) RETURNS BOOLEAN ->
    CASE
      WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN TRUE
      WHEN CURRENT_ROLE() = 'PAYMENTS_ANALYST' THEN TRUE
      WHEN CURRENT_ROLE() = 'PAYMENTS_READONLY' THEN COUNTRY_CODE = 'US'
      ELSE FALSE
    END;

ALTER TABLE DIM_CUSTOMER
  ADD ROW ACCESS POLICY RAP_COUNTRY_FILTER ON (COUNTRY_CODE);

